import ThemeRegistry from "@/theme/ThemeRegistry";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ReactQueryProvider } from "@/providers/ReactQuery";
import { ReduxProviders } from "@/providers/ReduxProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <ReactQueryProvider>
        <ReduxProviders>
          <html lang="en">
            <ThemeRegistry>
              <body className={roboto.className}>{children}</body>
            </ThemeRegistry>
          </html>
        </ReduxProviders>
      </ReactQueryProvider>
    </ClerkProvider>
  );
}
